[RFR] Second player win
marmelab/quixo-python pull request #9
Opened 2019-05-29 13:54 UTC by HALLERPierre

[Trello](https://trello.com/c/Qqm2ZmLM/17-as-thomas-if-align-5-circles-i-should-also-win-025)

# Done

- [x] Add check victory for the 2 playes (based on the numbers of rows)
- [x] Add tests for player 2 win

# Result

![2-players-win](https://user-images.githubusercontent.com/6030943/58562634-e80dcf80-8229-11e9-8f12-cb351e60c3a0.gif)

# Todo (next PR)

Refacto/Architecture

2019-05-29 14:12 UTC, jdemangeon approved these changes

2019-05-31 07:13 UTC, Luwangel approved these changes

2019-05-31 07:13 UTC, merged

2019-05-31 07:14 UTC, zyhou requested changes

2019-05-31 07:14 UTC, zyhou commented on src/game.py
> +    requirement = N_ROWS
Why create a `requirement` variable ?